application:
    name: Netatct Alarm Routing
server:
    port: 8888
    ssl:
        key-store: keystore.p12
        key-store-password: password
        keyStoreType: PKCS12
        keyAlias: tomcat
biz:
    futureware:
        mantis:
            rpc:
                soap:
                    client:
                           endpoint: http://gdcindonesia.com:8138/api/soap/mantisconnect.php


org:
    apache:
        axis:
            AxisProperties:
                    http:
                        proxy:
                            host: 10.144.1.10
                            port: 8080

# keytool -genkey -alias tomcat -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650